name = "ashlynn-bot"
type = "javascript"
account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2024-02-10"

# Define environment variables
[vars]
BOT_TOKEN = "your-bot-token"

# Define the D1 database
[[d1_databases]]
binding = "chat"
database_name = "ashlynn_repo"
database_id = "your-database-id"
